model: JEDILinearHGQ2
run_config :
  verbose : 2
  debug : True
  num_threads : 24

model_config :
  name : JEDILinear_HGQ2
  conv1d_layers : [10,10]
  classification_layers : [32,16]
  regression_layers : [10]
  beta: 1.1e-7

quantization_config:
  pt_output_quantization : [16,6]

training_config :
  weight_method: "onlyclass"
  epochs : 60
  batch_size : 512
  learning_rate : 0.003
  validation_split : 0.1

  loss_weights : [1,1]

firmware_config:
  input_precision: 'ap_fixed<24,12,AP_RND,AP_SAT>'
  class_precision: 'ap_ufixed<24,12,AP_RND,AP_SAT>'
  reg_precision: 'ap_fixed<16,6,AP_RND,AP_SAT>'

  clock_period : 2.5
  fpga_part : 'xcvu13p-flga2577-2-e'

  project_name: 'L1TSC4NGJetModel'
